### ISSUE TITLE
Fatal error: Class 'CsvImport_ColumnMap_MixElement' not found

### ISSUE THREAD

**Issue by JBPressac** [Daniel-KM/ArchiveFolder#1]
Hello,
I installed ArchiveFolder version 2.4 on Omeka 2.3.1 but when I try to add a new archive folder, the following error is displayed:

Fatal error: Class 'CsvImport_ColumnMap_MixElement' not found in /var/www/omeka/plugins/ArchiveFolder/libraries/ArchiveFolder/Form/Add.php on line 294

I am not a PHP developper, but it seems that there the class CsvImport_ColumnMap_MixElement is not defined in your plugin, while it is defined in your fork of [CsvImport](https://github.com/Daniel-KM/CsvImport/blob/master/models/CsvImport/ColumnMap/MixElement.php). Which means that [CsvImport](https://github.com/Daniel-KM/CsvImport/blob/master/models/CsvImport/ColumnMap/MixElement.php) is required ?
Thanks,

**Comment by Daniel-KM** [comment]
Hi, 

Thanks for your report. There isn't such dependency. This is a bug I just fixed!

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
