### ISSUE TITLE
Filenames are converted even when using utf8 compatible server. Error in parenthesis.

### ISSUE THREAD

**Issue by hydrosIII** [Daniel-KM/ArchiveFolder#4]
Hi. Currently I have an issue with this. It is a small error, but currently the plugin is turning all ( characters into [, and )  into ]. Thus modifying the names of the images. 

Thanks.

**Comment by Daniel-KM** [comment]
This renaming is set by default in the code to avoid some security issues.
But do you use the plugin ArchiveFolder or the plugin ArchiveRepertory?

**Comment by hydrosIII** [comment]
Ups, yes i openned this in wrong repo. I am speaking of Archive Repertory in Omeka-S. Sorry. I must have been asleep. I have posted the bug in the adequate repo.
